Repository adopted-ember-addons/ember-sortable, pull requests merged in 2019-10, with the labels that each got.

#265 Properly convert ScrollContainer width and height to integers
  addon/system/scroll-container.js
Labels: bug

#271 Modernizing test suite
  .huskyrc
  addon/components/sortable-group.js
  addon/components/sortable-item.js
  addon/helpers/drag.js
  addon/helpers/reorder.js
  addon/helpers/waiters.js
  package.json
  test-support/ember-sortable/helpers/drag.js
  test-support/ember-sortable/helpers/reorder.js
  test-support/ember-sortable/utils/offset.js
  test-support/helpers/ember-sortable/test-helpers.js
  tests/acceptance/smoke-test.js
  tests/dummy/app/templates/application.hbs
  tests/test-helper.js
  yarn.lock
Labels: enhancement

#287 Contextual components
  README.md
  addon/components/sortable-item.js
  addon/templates/components/sortable-group.hbs
  addon/templates/components/sortable-handle.hbs
  addon/templates/components/sortable-item.hbs
  tests/dummy/app/templates/application.hbs
  tests/integration/components/sortable-group-test.js
Labels: enhancement

#289 Adding sortable-handle
  addon/components/sortable-handle.js
  addon/components/sortable-item.js
  addon/templates/components/sortable-item.hbs
  app/components/sortable-handle.js
  tests/acceptance/smoke-test.js
  tests/dummy/app/templates/application.hbs
Labels: enhancement, internal
