Repository adopted-ember-addons/ember-sortable, pull requests merged in 2024-07, with the labels that each got.

#560 Add direction grid
  addon/src/modifiers/sortable-group.js
  addon/src/modifiers/sortable-item.js
  docs/app/controllers/index.js
  docs/app/routes/index.js
  docs/app/styles/app.css
  docs/app/templates/index.hbs
  docs/ember-cli-build.js
  test-app/app/controllers/index.js
  test-app/app/routes/index.js
  test-app/app/styles/app.css
  test-app/app/templates/index.hbs
  test-app/ember-cli-build.js
  test-app/tests/acceptance/smoke-modifier-test.js
Labels: enhancement

#566 Fix grid direction, when group element has negative margin
  addon/src/modifiers/sortable-group.js
  test-app/app/controllers/index.js
  test-app/app/routes/index.js
  test-app/app/styles/app.css
  test-app/app/templates/index.hbs
  test-app/tests/acceptance/smoke-modifier-test.js
Labels: bug

#571 fix demo links and turn of github pages deploy
  .github/workflows/deploy-gh-pages.yml
  README.md
  addon/package.json
Labels: internal

#572 Add info about `grid` direction into readme and minimal fixes
  README.md
Labels: documentation
